import { NextSeo } from 'next-seo';

import PageHeader from '../../components/page-header';
import Layout from '../../components/layout';
import { withGrid, PostGridItem } from '../../components/grid';

import { getFooterMenu } from '../../lib/Menus';
import { getLatestPosts } from '../../lib/Posts';

export default function PostsListTemplate({ menuItems, SSRPosts }) {
	const PostGrid = withGrid(PostGridItem);

	return (
		<Layout footerMenu={menuItems}>
			<NextSeo
				title="Decoupled Next WordPress - ISR Example"
				description="Generated by create next app."
			/>
			<PageHeader title="Posts" />
			<div className="mt-8 prose lg:prose-xl max-w-lg mx-auto lg:grid-cols-3 lg:max-w-screen-lg">
				<p>
					<em>
						By default, this starter kit is optimized for SSR and Edge Caching
						on Pantheon. This example instead uses Incremental Static
						Regeneration and is provided as a reference for cases where Next.js
						static generation options would be beneficial.
					</em>
				</p>
			</div>
			<section>
				<PostGrid contentType="posts" data={SSRPosts} />
			</section>
		</Layout>
	);
}

export async function getStaticProps() {
	const menuItems = await getFooterMenu();
	const SSRPosts = await getLatestPosts();

	return {
		props: {
			menuItems,
			SSRPosts,
		},
		revalidate: 60,
	};
}
