import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const cardStyle =
    "m-[1rem] p-[1.5rem] text-left no-underline border rounded-md max-w-[300px] transition transition-colors duration-150 ease-[cubic-bezier(0.25, 0.1, 0.25, 1.0)] hover:text-[#0070f3] hover:border-[#0070f3] focus:text-[#0070f3] focus:border-[#0070f3] active:text-[#0070f3] active:border-[#0070f3]";
  const cardH2Style = "mb-[1rem] text-2xl";
  const cardPStyle = "m-0 text-xl leading-6";

  return (
    <div className="px-[2rem] bg-white mt-[4rem] lg:mt-1">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-[100vh] px-[4rem] flex flex-col justify-center items-center">
        <h1 className="m-0 text-[4rem] no-underline text-center leading-[1.15rem]">
          Welcome to{" "}
          <a
            className="text-[#0070f3] hover:underline focus:underline active:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-[4rem] leading-6">
          Get started by editing{" "}
          <code className='bg-[#fafafa] rounded-2 p-[0.75rem] text-[1.1rem] font-mono'>pages/index.js</code>
        </p>

        <div className="flex lg:flex-row items-center justify-center flex-wrap lg:max-w-[800px]">
          <a href="https://nextjs.org/docs" className={cardStyle}>
            <h2 className={cardH2Style}>Documentation &rarr;</h2>
            <p className={cardPStyle}>
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={cardStyle}>
            <h2 className={cardH2Style}>Learn &rarr;</h2>
            <p className={cardPStyle}>
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={cardStyle}
          >
            <h2 className={cardH2Style}>Examples &rarr;</h2>
            <p className={cardPStyle}>
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cardStyle}
          >
            <h2 className={cardH2Style}>Deploy &rarr;</h2>
            <p className={cardPStyle}>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className='flex py-[2rem] border-y'>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center grow"
        >
          Powered by{" "}
          <span className="h-[3em] ml-[0.5rem] bg-black">
            <Image src="/pantheon.png" alt="Pantheon Logo" width={150} height={50} />
          </span>
        </a>
      </footer>
    </div>
  );
}
