packages: 
  - 'packages/**'
  - 'starters/**'
  - 'configs/**'
  - 'web'
  - '!packages/create-pantheon-decoupled-kit/__tests__/**'
  # prevents the ci-tests and ci-starters from using the root pnpm-lock.yaml
  - '!ci*'