import { NextSeo } from 'next-seo';
import { setEdgeHeader } from '@pantheon-systems/wordpress-kit';

import PageHeader from '../../components/page-header';
import Layout from '../../components/layout';
import { withGrid, PostGridItem } from '../../components/grid';
import { useRouter } from 'next/router';
import { Paginator } from '@pantheon-systems/nextjs-kit';
import Post from '../../components/post';

import { getFooterMenu } from '../../lib/Menus';
import { getLatestPosts, getPostBySlug } from '../../lib/Posts';

export default function PostHandler({ menuItems, posts }) {
	const router = useRouter();
	const { page = [] } = router.query;

	// render post list if multiple posts were passed
	if (posts.length !== undefined) {
		return (
			<PostsListTemplate
				menuItems={menuItems}
				posts={posts}
				pageNum={page[0]}
			/>
		);
	} else {
		return <PostTemplate menuItems={menuItems} post={posts} />;
	}
}

export function PostsListTemplate({ menuItems, posts, pageNum }) {
	const PostGrid = withGrid(PostGridItem);
	const RenderCurrentItems = ({ currentItems }) => {
		return (
			<PostGrid contentType="posts" data={currentItems} pageNum={pageNum} />
		);
	};

	return (
		<Layout footerMenu={menuItems}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create next app."
			/>

			<div className="prose max-w-max mx-auto">
				<section className="flex flex-col">
					<PageHeader title="Posts" />
					<Paginator
						data={posts}
						itemsPerPage={10}
						Component={RenderCurrentItems}
						routing
					/>
				</section>
			</div>
		</Layout>
	);
}

export function PostTemplate({ menuItems, post }) {
	return (
		<Layout footerMenu={menuItems}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create next app."
			/>
			<Post post={post} />
		</Layout>
	);
}

export async function getServerSideProps({ res, params }) {
	const menuItems = await getFooterMenu();
	let posts = await getLatestPosts();
	const { page } = params;

	if (page !== undefined) {
		// check if a specific post was requested
		posts = await getPostBySlug(page[page.length - 1]);
		if (posts === null) {
			posts = await getLatestPosts();
		}
	}

	setEdgeHeader({ res });

	return {
		props: {
			menuItems,
			posts,
		},
	};
}
