import { NextSeo } from 'next-seo';
import Layout from '../../components/layout';
import Post from '../../components/post';
import { ContentWithImage } from '@pantheon-systems/nextjs-kit';

import { getFooterMenu } from '../../lib/Menus';
import { getPostBySlug } from '../../lib/Posts';

export default function PostListTemplate({ menuItems, post }) {
	console.log(post);
	return (
		<Layout footerMenu={menuItems}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create next app."
			/>
			{/* <Post post={post} /> */}
			<ContentWithImage
				title={post.title}
				content={post.content}
				imageProps={{
					priority: true,
					src: post.featuredImage.node.sourceUrl,
					width: 200,
					height: 200,
				}}
			/>
		</Layout>
	);
}

export async function getServerSideProps({ params }) {
	const menuItems = await getFooterMenu();
	const { slug } = params;
	const post = await getPostBySlug(slug);

	if (!post) {
		return {
			notFound: true,
		};
	}

	return {
		props: {
			menuItems,
			post,
		},
	};
}
