import { NextSeo } from 'next-seo';
import { setEdgeHeader } from '@pantheon-systems/wordpress-kit';

import PageHeader from '../../components/page-header';
import Layout from '../../components/layout';
import { withGrid, PostGridItem } from '../../components/grid';

import { getFooterMenu } from '../../lib/Menus';
import { getLatestPosts } from '../../lib/Posts';

export default function PostsListTemplate({ menuItems, posts }) {
	const PostGrid = withGrid(PostGridItem);

	return (
		<Layout footerMenu={menuItems}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create next app."
			/>
			<PageHeader title="Posts" />
			<section>
				<PostGrid contentType="posts" data={posts} />
			</section>
		</Layout>
	);
}

export async function getServerSideProps({ res }) {
	const menuItems = await getFooterMenu();
	const posts = await getLatestPosts();
	setEdgeHeader({ res });

	return {
		props: {
			menuItems,
			posts,
		},
	};
}
