import { NextSeo } from "next-seo";

import PageHeader from "../../components/page-header.js";
import Layout from "../../components/layout";
import { getFooterMenu } from "../../lib/Menus.js";
import { withGrid, PostGridItem } from "../../components/grid.js";
import { getLatestPosts } from "../../lib/Posts.js";

export default function PostsListTemplate({ menuItems, SSRPosts }) {
  const PostGrid = withGrid(PostGridItem);

  return (
    <Layout footerMenu={menuItems}>
      <NextSeo
        title="Decoupled Next Drupal Demo"
        description="Generated by create next app."
      />
      <PageHeader title="Posts" />
      <section>
        <PostGrid contentType="posts" data={SSRPosts} />
      </section>
    </Layout>
  );
}

export async function getServerSideProps() {
  const menuItems = await getFooterMenu();
  const SSRPosts = await getLatestPosts();

  return {
    props: {
      menuItems,
      SSRPosts,
    },
  };
}
