import { NextSeo } from 'next-seo';
import Layout from '../../components/layout';
import PageHeader from '../../components/page-header';
import { getFooterMenu } from '../../lib/Menus';

export default function PageTemplate({ menuItems }) {
	return (
		<Layout footerMenu={menuItems}>
			<NextSeo
				title="Decoupled Next WordPress - Search"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<PageHeader title="Search Results" />
		</Layout>
	);
}

export async function getServerSideProps() {
	const { menuItems } = await getFooterMenu();

	return {
		props: {
			menuItems,
		},
	};
}
