import {
  getCurrentLocaleStore,
  globalDrupalStateAuthStores,
} from "../../lib/drupalStateContext";

import Head from "next/head";
import Link from "next/link";
import Layout from "../../components/layout";

export default function AuthApiExampleTemplate({ articles }) {
  return (
    <Layout>
      <Head>
        <title>API Authorization Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="prose lg:prose-xl mt-10 flex flex-col mx-auto max-h-screen">
        <h1>API Authorization Example</h1>

        <Link passHref href="/">
          <span className="w-full underline cursor-pointer">Home &rarr;</span>
        </Link>

        <div className="mt-12 max-w-lg mx-auto lg:grid-cols-3 lg:max-w-screen-lg">
          {articles.length > 0 && (
            <p>
               NextJS was able to successfuly make an authenticated request to
              Drupal!
            </p>
          )}
          {articles.length === 0 && (
            <p>
              NextJS was unable to make an authorized request to the Drupal API.
              Please check your .env file to ensure that your CLIENT_ID and
              CLIENT_SECRET are set correctly.
            </p>
          )}
        </div>
      </div>
    </Layout>
  );
}

export async function getStaticProps({ locale }) {
  const authstore = getCurrentLocaleStore(locale, globalDrupalStateAuthStores);

  authstore.params.clear();
  const articles = await authstore.getObject({
    objectName: "node--article",
  });
  return {
    props: {
      articles,
      revalidate: 60,
    },
  };
}
