import Head from 'next/head';
import Link from 'next/link';
import Layout from '../../components/layout';

import {
	getCurrentLocaleStore,
	globalDrupalStateStores,
} from '../../lib/stores';
import { BUILD_MODE } from '../../lib/constants';

export default function ExamplesPageTemplate({ footerMenu }) {
	return (
		<Layout footerMenu={footerMenu}>
			<Head>
				<title>Examples</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="prose lg:prose-xl mt-10 flex flex-col mx-auto max-h-screen">
				<h1>Examples</h1>

				<Link passHref href="/">
					<span className="w-full underline cursor-pointer">Home &rarr;</span>
				</Link>

				<div className="max-w-lg mx-auto lg:grid-cols-3 lg:max-w-screen-lg">
					<p>
						This page outlines a growing list of common use cases that can be
						used as a reference when building using this starter kit. If you
						don&apos;t need them for your site, feel free to delete the
						`pages/examples` directory in your codebase.
					</p>
					<ul>
						<li>
							<Link href="/examples/auth-api">API Authorization</Link> -
							confirms that Next.js is able to make authenticated requests to
							Drupal&apos;s API.
						</li>
						<li>
							<Link href="/examples/ssg-isr">SSG and ISR</Link> - by default,
							this starter kit is optimized for SSR and Edge Caching on
							Pantheon. This example is provided for cases where Next.js static
							generation options would be beneficial.
						</li>
						<li>
							<Link href="/examples/pagination">Pagination</Link> - a paginated
							list with a large dataset.
						</li>
					</ul>
				</div>
			</div>
		</Layout>
	);
}

export async function getStaticProps(context) {
	const { locale } = context;
	const store = getCurrentLocaleStore(locale, globalDrupalStateStores);

	try {
		const footerMenu = await store.getObject({
			objectName: 'menu_items--main',
			refresh: !BUILD_MODE,
			anon: true,
		});

		return {
			props: {
				footerMenu,
			},
			revalidate: 60,
		};
	} catch (error) {
		console.error(error);
	}
}
