import { sortDate } from '@pantheon-systems/nextjs-kit';
import { NextSeo } from 'next-seo';
import { isMultiLanguage } from '../lib/isMultiLanguage';
import { getCurrentLocaleStore, globalDrupalStateStores } from '../lib/stores';

import Image from 'next/image';
import { ArticleGrid } from '../components/grid';
import Layout from '../components/layout';
import styles from './index.module.css';

export default function HomepageTemplate({
	sortedArticles,
	footerMenu,
	hrefLang,
	multiLanguage,
}) {
	const HomepageHeader = () => (
		<div className={styles.header}>
			<h1>
				Welcome to{' '}
				<a className={styles.next} href="https://nextjs.org">
					Next.js!
				</a>
			</h1>
			<div className={styles.onPantheon}>
				<span>Decoupled Drupal on </span>
				<Image
					src="/pantheon.png"
					alt="Pantheon Logo"
					style={{
						margin: 0,
					}}
					width={191}
					height={60}
				/>
			</div>
		</div>
	);

	return (
		<Layout footerMenu={footerMenu}>
			<NextSeo
				title="Decoupled Next Drupal Demo"
				description="Generated by create-pantheon-decoupled-kit."
				languageAlternates={hrefLang || false}
			/>
			<>
				<HomepageHeader />
				<section>
					<ArticleGrid
						data={sortedArticles}
						contentType="articles"
						multiLanguage={multiLanguage}
					/>
				</section>
			</>
		</Layout>
	);
}

export async function getServerSideProps(context) {
	const origin = process.env.NEXT_PUBLIC_FRONTEND_URL;
	const { locales } = context;
	// if there is more than one language in context.locales,
	// assume multilanguage is enabled.
	const multiLanguage = isMultiLanguage(locales);
	const hrefLang = locales.map((locale) => {
		return {
			hrefLang: locale,
			href: origin + '/' + locale,
		};
	});

	try {
		const store = getCurrentLocaleStore(
			context.locale,
			globalDrupalStateStores,
		);

		const articles = await store.getObject({
			objectName: 'node--article',
			params: 'include=field_media_image.field_media_image',
			refresh: true,
			res: context.res,
			anon: true,
		});

		if (!articles) {
			throw new Error(
				'No articles returned. Make sure the objectName and params are valid!',
			);
		}

		const sortedArticles = sortDate({
			data: articles,
			key: 'changed',
			direction: 'desc',
		});

		const footerMenu = await store.getObject({
			objectName: 'menu_items--main',
			refresh: true,
			res: context.res,
			anon: true,
		});

		return {
			props: { sortedArticles, hrefLang, multiLanguage, footerMenu },
		};
	} catch (error) {
		console.error('Unable to fetch data for articles page: ', error);
		return {
			notFound: true,
		};
	}
}
