// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footer: string;
export const footerNav: string;
export const footerUl: string;
export const navItem: string;
export const navItemLink: string;
export const footerCopy: string;
export const footerCopyLink: string;
export const footerCopyLinks: string;
