// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const gradientPlaceholder: string;
export const container: string;
export const card: string;
export const cardTitle: string;
export const cardImg: string;
export const notFound: string;
