// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const layout: string;
export const navLinks: string;
export const links: string;
export const layoutMain: string;
