// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const mainTitle: string;
export const link: string;
export const date: string;
export const content: string;
export const paragraphContent: string;
export const img: string;
export const hr: string;
export const nav: string;
export const prev: string;
export const next: string;
export const containerTitle: string;
