// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const pageCount: string;
export const btnContainer: string;
export const btnList: string;
export const paginatorBtn: string;
export const directionalBtns: string;
export const separatorBtn: string;
