import { NextSeo } from 'next-seo';
import Link from 'next/link';
import Layout from '../../components/layout';
import PageHeader from '../../components/page-header';
import { BUILD_MODE } from '../../lib/constants';
import {
	getCurrentLocaleStore,
	globalDrupalStateStores,
} from '../../lib/stores';
import styles from './index.module.css';

export default function ExamplesPageTemplate({ footerMenu }) {
	return (
		<Layout footerMenu={footerMenu}>
			<NextSeo
				title="Decoupled Next Drupal - Examples"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<PageHeader title="Examples" />
			<section className={styles.container}>
				<div className={styles.content}>
					<Link passHref href="/">
						<span>Home &rarr;</span>
					</Link>
					<p>
						This page outlines a growing list of common use cases that can be
						used as a reference when building using this starter kit. If you
						don&apos;t need them for your site, feel free to delete the
						`pages/examples` directory in your codebase.
					</p>
					<ul>
						<li>
							<Link href="/examples/auth-api">API Authorization</Link> -
							confirms that Next.js is able to make authenticated requests to
							Drupal&apos;s API.
						</li>
						<li>
							<Link href="/examples/ssg-isr">SSG and ISR</Link> - by default,
							this starter kit is optimized for SSR and Edge Caching on
							Pantheon. This example is provided for cases where Next.js static
							generation options would be beneficial.
						</li>
						<li>
							<Link href="/examples/pagination">Pagination</Link> - a paginated
							list with a large dataset.
						</li>
					</ul>
				</div>
			</section>
		</Layout>
	);
}

export async function getStaticProps(context) {
	const { locale } = context;
	const store = getCurrentLocaleStore(locale, globalDrupalStateStores);

	try {
		const footerMenu = await store.getObject({
			objectName: 'menu_items--main',
			refresh: !BUILD_MODE,
			anon: true,
		});

		return {
			props: {
				footerMenu,
			},
			revalidate: 60,
		};
	} catch (error) {
		console.error(error);
	}
}
