import { setOutgoingHeaders } from '@pantheon-systems/wordpress-kit';
import { NextSeo } from 'next-seo';
import Image from 'next/image';
import { PostGrid } from '../components/grid';
import Layout from '../components/layout';
import { getFooterMenu, getHeaderMenu } from '../lib/Menus';
import { getLatestPosts } from '../lib/Posts';
import styles from './index.module.css';

export default function Home({ footerMenuItems, headerMenuItems, posts }) {
	const HomepageHeader = () => (
		<div className={styles.header}>
			<h1>
				Welcome to{' '}
				<a className={styles.next} href="https://nextjs.org">
					Next.js!
				</a>
			</h1>
			<div className={styles.onPantheon}>
				<span>Decoupled WordPress on </span>
				<Image
					src="/pantheon.png"
					alt="Pantheon Logo"
					style={{
						margin: 0,
					}}
					width={191}
					height={60}
				/>
			</div>
		</div>
	);

	return (
		<Layout footerMenu={footerMenuItems} mainNavItems={headerMenuItems}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<HomepageHeader />
			<section>
				<PostGrid contentType="posts" data={posts} />
			</section>
		</Layout>
	);
}

export async function getServerSideProps({ res }) {
	const { footerMenuItems, footerMenuItemHeaders } = await getFooterMenu();
	const { headerMenuItems, headerMenuItemHeaders } =
		await getHeaderMenu('Example Menu');
	const { posts, headers: postHeaders } = await getLatestPosts(12);

	const headers = [footerMenuItemHeaders, headerMenuItemHeaders, postHeaders];
	setOutgoingHeaders({ headers, res });

	return {
		props: {
			footerMenuItems,
			headerMenuItems,
			posts,
		},
	};
}
