// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const containerTitle: string;
export const link: string;
export const content: string;
export const paragraph: string;
