// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const headerTitle: string;
export const gatsby: string;
export const onPantheon: string;
