// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const content: string;
export const title: string;
export const item: string;
export const itemTitle: string;
export const noData: string;
export const link: string;
