import { NextSeo } from "next-seo";
import Layout from "../../components/layout";
import PageHeader from "../../components/page-header.js";
import { client } from "../../lib/WordpressClient";
import { gql } from "@pantheon-systems/wordpress-kit";

export default function PageListTemplate({ menuItems }) {
  return (
    <Layout footerMenu={menuItems}>
      <NextSeo
        title="Decoupled Next Drupal Demo"
        description="Generated by create next app."
      />
      <PageHeader title="Pages" />
      <section>
        <div className="mt-20 flex justify-center">
          <span className="text-3xl">
            🚧 This is a placeholder for the pages list.
          </span>
        </div>
      </section>
    </Layout>
  );
}

export async function getStaticProps() {
  const query = gql`
    query FooterMenuQuery {
      menus(where: { location: FOOTER }) {
        edges {
          node {
            id
            menuItems {
              edges {
                node {
                  id
                  uri
                  label
                }
              }
            }
          }
        }
      }
    }
  `;

  const data = await client.request(query);

  const footerMenu = data.menus.edges.flatMap((node) => {
    return node.node.menuItems.edges.map((menuItem) => {
      return menuItem.node;
    });
  });

  return {
    props: {
      menuItems: footerMenu,
    },
  };
}
