import { NextSeo } from 'next-seo';
import { setOutgoingHeaders } from '../../lib/setOutgoingHeaders';

import { PageGridItem } from '../../components/grid';
import { withGrid, Paginator } from '@pantheon-systems/nextjs-kit';
import Layout from '../../components/layout';
import PageHeader from '../../components/page-header';

import { getFooterMenu } from '../../lib/Menus';
import { getLatestPages } from '../../lib/Pages';

export default function PageListTemplate({ menuItems, pages }) {
	const PagesGrid = withGrid(PageGridItem);

	const RenderCurrentItems = ({ currentItems }) => {
		return <PagesGrid contentType="pages" data={currentItems} />;
	};

	return (
		<Layout footerMenu={menuItems}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create next app."
			/>
			<div className="max-w-screen-lg mx-auto">
				<section>
					<PageHeader title="Pages" />
					<Paginator
						data={pages}
						itemsPerPage={12}
						Component={RenderCurrentItems}
					/>
				</section>
			</div>
		</Layout>
	);
}

export async function getServerSideProps({ res }) {
	const { menuItems, menuItemHeaders } = await getFooterMenu();
	const { pages, headers: pageHeaders } = await getLatestPages(100);

	const headers = [menuItemHeaders, pageHeaders];
	setOutgoingHeaders({ headers, res });

	return {
		props: {
			menuItems,
			pages,
		},
	};
}
