import { NextSeo } from "next-seo";
import Layout from "../../components/layout";
import PageHeader from "../../components/page-header.js";
import { getFooterMenu } from "../../lib/Menus";

export default function PageListTemplate({ menuItems }) {
  return (
    <Layout footerMenu={menuItems}>
      <NextSeo
        title="Decoupled Next Drupal Demo"
        description="Generated by create next app."
      />
      <PageHeader title="Pages" />
      <section>
        <div className="mt-20 flex justify-center">
          <span className="text-3xl">
            🚧 This is a placeholder for the pages list.
          </span>
        </div>
      </section>
    </Layout>
  );
}

export async function getStaticProps() {
  const menuItems = await getFooterMenu();

  return {
    props: {
      menuItems,
    },
  };
}
