#!/bin/sh

if [ "$CI" = "true" ]; then
  pnpm build:pkgs
  else
	pnpm check-built
fi

readonly isHooksInstalled="$(git config --get-all core.hooksPath | grep -c .husky)"
if [ "$isHooksInstalled" = "0" ]; then
  echo "🐾  Installing git hooks..."
  pnpm husky install
fi
