export const CMS_ENV_VARS = {
	BACKEND_URL: 'BACKEND_URL',
	PANTHEON_CMS_ENDPOINT: 'PANTHEON_CMS_ENDPOINT',
};
export const AUTH_ENV_VARS = ['CLIENT_ID', 'CLIENT_SECRET'];
export const PREVIEW_ENV_VARS = ['PREVIEW_SECRET'] as const;
