#!/bin/sh
[ -n "$CI" ] && exit 0
. "$(dirname "$0")/_/husky.sh"

pnpm --workspace-concurrency=1 --filter './packages/**' lint-staged
pnpm --filter './packages/**' test
pnpm generate-starters
pnpm i --ignore-scripts
pnpm --filter './starters/**' test
rm -r ./starters
rm pnpm-lock.yaml
pnpm i --ignore-scripts