export const nextWpPageView = () => /* tsx */ `
import { setOutgoingHeaders } from '@pantheon-systems/wordpress-kit';
import { ContentWithImage } from '@pantheon-systems/nextjs-kit';
import { NextSeo } from 'next-seo';
import Layout from '../../components/layout';

import { getFooterMenu, getHeaderMenu } from '../../lib/Menus';
import { getPageByUri, getPagePreview } from '../../lib/Pages';
import styles from './page.module.css';

export default function PageTemplate({ footerMenuItems, headerMenuItems, page, preview }) {
	return (
		<Layout footerMenu={footerMenuItems} mainNavItems={headerMenuItems} preview={preview}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<ContentWithImage
				title={page.title}
				content={page.content}
				date={new Date(page.date).toDateString()}
				imageProps={
					page.featuredImage
						? {
								src: page.featuredImage?.node.sourceUrl,
								alt: page.featuredImage?.node.altText,
							}
						: undefined
					}
					contentClassName={styles.content}
			/>
		</Layout>
	);
}
export async function getServerSideProps({
	params: { uri },
	res,
	preview,
	previewData,
}) {
	const { footerMenuItems, footerMenuItemHeaders } = await getFooterMenu();
	const { headerMenuItems, headerMenuItemHeaders } =
		await getHeaderMenu('Example Menu');
	const { page, headers: pageHeaders = false } = preview
		? await getPagePreview(previewData.key)
		: await getPageByUri(uri);

	if (!page) {
		return {
			notFound: true,
		};
	}

	const headers = pageHeaders && [footerMenuItemHeaders, headerMenuItemHeaders, pageHeaders];
	headers.length > 0 && setOutgoingHeaders({ headers, res });

	return {
		props: {
			footerMenuItems,
			headerMenuItems,
			page,
			preview: Boolean(preview),
		},
	};
}
`;
