import { taggedTemplateHelpers as utils } from '@cli/utils';

const relatedContentJSX = /* tsx */ `{post.relatedContent?.relatedPosts ? (
	<section>
		<header className={styles.acfHeader}>
			<h2>Related Content</h2>
		</header>
		<PostGrid
			contentType="posts"
			data={post.relatedContent.relatedPosts}
		/>
	</section>
) : null}`;

export const nextWpPostView = (wpAcfAddon: boolean) => /* tsx */ `
import { setOutgoingHeaders } from '@pantheon-systems/wordpress-kit';
import { ContentWithImage } from '@pantheon-systems/nextjs-kit';
import { NextSeo } from 'next-seo';

import Layout from '../../components/layout';
import { getFooterMenu, getHeaderMenu } from '../../lib/Menus';
import { getPostByUri, getPostPreview } from '../../lib/Posts';
${utils.if(
	wpAcfAddon,
	/* ts */ `import { PostGrid } from '../../components/grid';`,
)}
import styles from './[...slug].module.css';

export default function PostTemplate({ footerMenuItems, headerMenuItems, post, preview }) {
	return (
		<Layout footerMenu={footerMenuItems} mainNavItems={headerMenuItems} preview={preview}>
			<NextSeo
				title="Decoupled Next WordPress Demo"
				description="Generated by create-pantheon-decoupled-kit."
			/>
			<ContentWithImage
				title={post.title}
				content={post.content}
				date={new Date(post.date).toDateString()}
				imageProps={
					post.featuredImage
						? {
								src: post?.featuredImage?.node.sourceUrl,
								alt: post?.featuredImage?.node.altText,
						  }
						: undefined
				}
				contentClassName={styles.content}
			/>
			${utils.if(wpAcfAddon, relatedContentJSX)}
		</Layout>
	);
}

export async function getServerSideProps({
	params: { slug },
	res,
	preview,
	previewData,
}) {
	const { footerMenuItems, footerMenuItemHeaders } = await getFooterMenu();
	const { headerMenuItems, headerMenuItemHeaders } =
		await getHeaderMenu('Example Menu');
	const { post, headers: postHeaders = false } = preview
		? await getPostPreview(previewData.key)
		: await getPostByUri(slug);

	if (!post) {
		return {
			notFound: true,
		};
	}

	const headers = postHeaders && [footerMenuItemHeaders, headerMenuItemHeaders, postHeaders];
	headers.length > 0 && setOutgoingHeaders({ headers, res });

	return {
		props: {
			footerMenuItems,
			headerMenuItems,
			post,
			preview: Boolean(preview),
		},
	};
}
`;
