name: Headless Regression Testing

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  # test branch
  push:
    branches:
      - feat/cli-regression-tests

jobs:
  cli-regression-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # define package to repository map
        include:
          # next-drupal-starter-search
          - local_path: 'starters/next-drupal-search'
            label: 'next-drupal-search'
            generator_cmd: 'next-drupal next-drupal-umami-addon next-drupal-search-api-addon --appName @pantheon-systems/next-drupal-search-starter --cmsEndpoint ${{ vars.BACKEND_URL }} --tailwindcss --force --silent --noInstall'
            test_cmd: test:next-drupal-search
            start_cmd: HOSTNAME=0.0.0.0 npm run start
            # gatsby-wordpress-starter example matrix entry
          - local_path: 'starters/gatsby-wordpress-starter-generated'
            label: 'gatsby-wordpress-starter'
            generator_cmd: 'gatsby-wp --appName @pantheon-systems/gatsby-wordpress-starter --cmsEndpoint ${{ vars.WPGRAPHQL_URL }} --tailwindcss --force --silent --noInstall'
            test_cmd: test:gatsby-wp
            start_cmd: npm run serve
            # next-wordpress-starter example matrix entry
          - local_path: 'starters/next-wordpress-starter-generated'
            label: 'next-wordpress-starter'
            generator_cmd: 'next-wp --appName @pantheon-systems/next-wordpress-starter --cmsEndpoint ${{ vars.WPGRAPHQL_URL }} --tailwindcss --force --silent --noInstall'
            test_cmd: test:next-wp
            start_cmd: HOSTNAME=0.0.0.0 npm run start
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        uses: ./.github/actions/setup-playwright
        with:
          local_path: ${{ matrix.local_path }}

      # run the command to generate the starter in the matrix.local_path directory
      - name: Generate starter
        run: pnpm create-pantheon-decoupled-kit ${{ matrix.generator_cmd }} --outDir ~/${{ matrix.local_path }}

      - name: Build and run the starter
        run: |
          REPO_PATH=$(pwd)
          cd ~/${{ matrix.local_path }}
          npm install
          npm run build
          ${{ matrix.start_cmd }} &
          cd $REPO_PATH

      - name: Cache generated starter
        uses: actions/cache/save@v3
        id: cache-starter-save
        with:
          path: ./${{ matrix.local_path }}
          key: ${{ steps.setup.outputs.starter-cache-key }}

      - name: Run tests
        run: npm run ${{ matrix.test_cmd }}

      - name: Commit new or updated snapshots
        if: always()
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: './ci-tests'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: pantheon-decoupled-service-user

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: decoupled-service-user@pantheon.io

          # The name of the custom committer you want to use, if different from the author of the commit.
          # Default: the name of the author (set with either author_name or default_author)
          committer_name: pantheon-decoupled-service-user

          # The email of the custom committer you want to use, if different from the author of the commit.
          # Default: the email of the author (set with either author_email or default_author)
          committer_email: decoupled-service-user@pantheon.io
          cwd: './'
          fetch: --all
          message: Update ${{ matrix.label }} snapshot
          pathspec_error_handling: ignore

          # Arguments for the git pull command. By default, the action does not pull.
          # Default: ''
          # pull: "--ff"
          push: true
          # Arguments for the git push --tags command (any additional argument will be added after --tags)
          # Default: ''
          # tag_push: '--force'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
